### GET ALL POSTS
GET http://localhost:4000/posts

### GET A SINGLE POST
GET http://localhost:4000/posts/1

### CREATE POST
POST http://localhost:4000/posts
content-Type: application/json

{
    "title":"new post title",
    "likes":0
}

### UPDATE POST
PUT http://localhost:4000/posts/1
content-Type: application/json

{
    "title":"updated title",
    "likes":100
}

### DELETE POST
DELETE http://localhost:4000/posts/1